### ISSUE TITLE
The bld/cvmix_setup script uses python 2

### ISSUE THREAD

**Issue by glwagner** [CVMix/CVMix-src#77]
Which means that `make` in `/src` fails when the system python is python3.

**Comment by glwagner** [comment]
An easy fix is to change the shebang idiom at the top of `cvmix_setup` to

`#!/usr/bin/env python2`

which works if the shell command `python2` points to a python 2 executable.

**Comment by mnlevy1981** [comment]
Thanks for letting me know, I had a hunch that #76 was just the beginning of py3 incompatibilities - I'll try to push a fix by the end of the day (and set up some continuous integration per #75 to ensure everything continues to run correctly in the future)

**Comment by glwagner** [comment]
Sounds great!

**Comment by mnlevy1981** [comment]
Closed via #78 (python 3 support begins with [v0.95-beta](https://github.com/CVMix/CVMix-src/releases/tag/v0.95-beta))
